In [1]:
import numpy as np

In [10]:
np.random.seed(42)
x = np.random.randint(0,5,(3,10))
x

array([[3, 4, 2, 4, 4, 1, 2, 2, 2, 4],
       [3, 2, 4, 1, 3, 1, 3, 4, 0, 3],
       [1, 4, 3, 0, 0, 2, 2, 1, 3, 3]])

In [11]:
y=np.array([0,4,2])

In [12]:
np.in1d(x,y)

array([False,  True,  True,  True,  True, False,  True,  True,  True,
        True, False,  True,  True, False, False, False, False,  True,
        True, False, False,  True, False,  True,  True,  True,  True,
       False, False, False])

In [13]:
np.isin(x,y)

array([[False,  True,  True,  True,  True, False,  True,  True,  True,
         True],
       [False,  True,  True, False, False, False, False,  True,  True,
        False],
       [False,  True, False,  True,  True,  True,  True, False, False,
        False]])