In [1]:
import numpy as np

In [2]:
# Filling the question from 
# https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [3]:
# Question1:

print(np.__version__)

1.24.3


In [7]:
#Q2

x = np.arange(9)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [16]:
#Q3

x = np.ones((3,3), dtype=np.bool_)
x

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:
#Q4

arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[arr%2==1]

array([1, 3, 5, 7, 9])

In [23]:
#Q5
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [25]:
#Q6
arr = np.arange(10)
out = np.copy(arr)
out[out%2==1]=-1

print('arr: {}'.format(arr))
print('out: {}'.format(out))

arr: [0 1 2 3 4 5 6 7 8 9]
out: [ 0 -1  2 -1  4 -1  6 -1  8 -1]


In [30]:
out = np.where(arr%2==1, -1, arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [33]:
#Q7

x = np.arange(24).reshape(4,6)
x

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [34]:
#Q8

a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

In [36]:
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [38]:
np.concatenate((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [40]:
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [41]:
#Q9 

a = np.arange(10).reshape(2,-1)

b = np.repeat(1, 10).reshape(2,-1)

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [42]:
np.concatenate([a,b], axis=1)

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [43]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [49]:
#Q10

a = np.array([1, 2, 3])
b = np.repeat(a, 3)
c = np.tile(a,3)
d = np.hstack((b,c))
d

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [52]:
#Q11

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.intersect1d(a,b)

array([2, 4])

In [54]:
#Q12

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [55]:
np.setxor1d(a,b)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [56]:
#Q13

a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

np.where(a==b)

(array([1, 3, 5, 7]),)

In [66]:
#Q14

a = np.array([2, 6, 1, 9, 10, 3, 27])

ind = np.where((a>=5)&(a<=10))[:]
a[ind]

array([ 6,  9, 10])

In [60]:
help(np.logical_and

TypeError: logical_and() takes from 2 to 3 positional arguments but 0 were given

In [67]:
#Q15

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
    
pair_max = np.vectorize(maxx)    

In [72]:
pair_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [76]:
#Q16

arr = np.arange(12).reshape(3,4)
print(arr)
np.swapaxes(arr, axis1=0, axis2=1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [78]:
arr[:, [0, 2, 1, 3]]

array([[ 0,  2,  1,  3],
       [ 4,  6,  5,  7],
       [ 8, 10,  9, 11]])

In [80]:
#Q17

arr = np.arange(9).reshape(3,3)

arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [81]:
arr[[0,2,1],:]

array([[0, 1, 2],
       [6, 7, 8],
       [3, 4, 5]])

In [82]:
#Q18

arr[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [83]:
np.flip(arr)

array([[8, 7, 6],
       [5, 4, 3],
       [2, 1, 0]])

In [84]:
#Q19 

arr[:, ::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [91]:
#Q20

arr = np.random.randint(5,10,(5,3))+np.random.random((5,3))
arr

array([[6.08822681, 5.47280402, 7.28193387],
       [9.86009739, 8.82572743, 6.41189543],
       [9.76037603, 6.12551376, 5.97655969],
       [7.67956714, 7.07290403, 5.78952398],
       [7.1880862 , 5.74692421, 7.61282679]])

In [94]:
arr = np.random.uniform(5,10,(5,3))
arr

array([[6.91957004, 6.65203819, 7.44006541],
       [9.96804652, 9.11046638, 9.74215544],
       [8.57850311, 8.86149758, 6.91217984],
       [5.50270799, 9.60113497, 6.2943649 ],
       [6.25097944, 8.55915091, 9.48684799]])

In [95]:
help(np.random.choice)

Help on built-in function choice:

choice(...) method of numpy.random.mtrand.RandomState instance
    choice(a, size=None, replace=True, p=None)
    
    Generates a random sample from a given 1-D array
    
    .. versionadded:: 1.7.0
    
    .. note::
        New code should use the `~numpy.random.Generator.choice`
        method of a `~numpy.random.Generator` instance instead;
        please see the :ref:`random-quick-start`.
    
    Parameters
    ----------
    a : 1-D array-like or int
        If an ndarray, a random sample is generated from its elements.
        If an int, the random sample is generated as if it were ``np.arange(a)``
    size : int or tuple of ints, optional
        Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
        ``m * n * k`` samples are drawn.  Default is None, in which case a
        single value is returned.
    replace : boolean, optional
        Whether the sample is with or without replacement. Default is True,
        meaning th

In [96]:
#Q21

np.round(arr, 3)

array([[6.92 , 6.652, 7.44 ],
       [9.968, 9.11 , 9.742],
       [8.579, 8.861, 6.912],
       [5.503, 9.601, 6.294],
       [6.251, 8.559, 9.487]])

In [101]:
#Q22
np.set_printoptions(suppress=True, precision=6)  # precision is optional

np.random.seed(100)
rand_arr = np.random.random([3,3])/1e3
rand_arr

print(rand_arr)

[[0.000543 0.000278 0.000425]
 [0.000845 0.000005 0.000122]
 [0.000671 0.000826 0.000137]]


In [103]:
#Q23
np.set_printoptions(threshold=6)
print(np.arange(18))

[ 0  1  2 ... 15 16 17]


In [108]:
#Q24
a=np.arange(15)
np.set_printoptions(threshold=np.nan)

print(a)

ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation

In [ ]:
#Q25

